package com.aicrm.platform.application;
import com.aicrm.kernel.error.*; import com.aicrm.kernel.event.DomainEvent; import com.aicrm.kernel.id.IdGenerator; import com.aicrm.kernel.security.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class SalesDocumentService {
 public record Document(long id,String title,String category,String content,Status status,long ownerUserId,Instant publishedAt,Instant archivedAt,long version) { public enum Status { DRAFT,PUBLISHED,ARCHIVED } }
 public record Create(String title,String category,String content){} public record Versioned(long version){}
 private final JdbcTemplate jdbc;private final IdGenerator ids;private final IdempotencyService idem;private final AuditLogService audit;private final OutboxService outbox;private final ObjectMapper mapper;
 public SalesDocumentService(JdbcTemplate jdbc,IdGenerator ids,IdempotencyService idem,AuditLogService audit,OutboxService outbox,ObjectMapper mapper){this.jdbc=jdbc;this.ids=ids;this.idem=idem;this.audit=audit;this.outbox=outbox;this.mapper=mapper;}
 @Transactional public Document create(Actor a,Create c,String key){manage(a);return idem.execute(a,"document:create",key,c,Document.class,()->{Document d=new Document(ids.nextId(),req(c.title(),200,"标题"),req(c.category(),64,"分类"),req(c.content(),20000,"内容"),Document.Status.DRAFT,a.userId(),null,null,0);jdbc.update("insert into crm_sales_document(id,tenant_id,title,category,content,status,owner_user_id,version,created_by,updated_by)values(?,?,?,?,?,'DRAFT',?,?,?,?)",d.id(),a.tenantId(),d.title(),d.category(),d.content(),a.userId(),0,a.userId(),a.userId());journal(a,"CREATE",d,"SalesDocumentCreated");return d;});}
 public Document get(Actor a,long id){read(a);return find(a,id);} public List<Document> list(Actor a){read(a);return jdbc.query("select * from crm_sales_document where tenant_id=? and deleted_at is null order by updated_at desc,id desc",(rs,n)->map(rs),a.tenantId());}
 @Transactional public Document publish(Actor a,long id,Versioned c){return transition(a,id,c,Document.Status.DRAFT,Document.Status.PUBLISHED,"PUBLISH","SalesDocumentPublished");} @Transactional public Document archive(Actor a,long id,Versioned c){return transition(a,id,c,Document.Status.PUBLISHED,Document.Status.ARCHIVED,"ARCHIVE","SalesDocumentArchived");}
 private Document transition(Actor a,long id,Versioned c,Document.Status from,Document.Status to,String action,String event){manage(a);Document before=find(a,id);if(jdbc.update("update crm_sales_document set status=?,published_at=case when ?='PUBLISHED' then now() else published_at end,archived_at=case when ?='ARCHIVED' then now() else null end,version=version+1,updated_by=?,updated_at=now() where tenant_id=? and id=? and status=? and version=? and deleted_at is null",to.name(),to.name(),to.name(),a.userId(),a.tenantId(),id,from.name(),c.version())!=1)throw new DomainException(ErrorCode.CONFLICT,"文档状态已变化，请刷新后重试");Document after=find(a,id);journal(a,action,after,event);return after;}
 private Document find(Actor a,long id){List<Document>x=jdbc.query("select * from crm_sales_document where tenant_id=? and id=? and deleted_at is null",(rs,n)->map(rs),a.tenantId(),id);if(x.isEmpty())throw new DomainException(ErrorCode.NOT_FOUND,"销售资料不存在");return x.get(0);}private Document map(java.sql.ResultSet rs)throws java.sql.SQLException{var p=rs.getTimestamp("published_at");var ar=rs.getTimestamp("archived_at");return new Document(rs.getLong("id"),rs.getString("title"),rs.getString("category"),rs.getString("content"),Document.Status.valueOf(rs.getString("status")),rs.getLong("owner_user_id"),p==null?null:p.toInstant(),ar==null?null:ar.toInstant(),rs.getLong("version"));}private void read(Actor a){if(!a.hasPermission("document:read")&&!a.hasPermission("document:manage"))throw new DomainException(ErrorCode.FORBIDDEN,"缺少权限：document:read");}private void manage(Actor a){if(!a.hasPermission("document:manage"))throw new DomainException(ErrorCode.FORBIDDEN,"缺少权限：document:manage");}private String req(String s,int max,String name){if(s==null||s.isBlank())throw new DomainException(ErrorCode.VALIDATION_ERROR,name+"不能为空");s=s.trim();if(s.length()>max)throw new DomainException(ErrorCode.VALIDATION_ERROR,name+"长度超限");return s;}private void journal(Actor a,String action,Document d,String e){try{String x=mapper.writeValueAsString(d),op="document:"+action+":"+ids.nextId();audit.record(a,action,"SALES_DOCUMENT",d.id(),op,"API",null,"{}",x);outbox.append(new DomainEvent(e,"SALES_DOCUMENT",d.id(),a.tenantId(),x,Instant.now()),op,a.userId());}catch(Exception ex){throw new IllegalStateException(ex);}}
}
