package com.aicrm.sales.application;
import com.aicrm.kernel.error.*; import com.aicrm.kernel.event.DomainEvent; import com.aicrm.kernel.id.IdGenerator; import com.aicrm.kernel.security.*; import com.aicrm.platform.application.*; import com.aicrm.sales.domain.SalesRepository; import com.aicrm.sales.domain.conversation.*; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant;
@Service public class SalesConversationService {
 private final SalesConversationRepository repo; private final SalesReadService sales; private final SalesRepository salesRepository; private final IdGenerator ids; private final IdempotencyService idem; private final AuditLogService audit; private final OutboxService outbox; private final ObjectMapper mapper;
 public SalesConversationService(SalesConversationRepository repo,SalesReadService sales,SalesRepository salesRepository,IdGenerator ids,IdempotencyService idem,AuditLogService audit,OutboxService outbox,ObjectMapper mapper){this.repo=repo;this.sales=sales;this.salesRepository=salesRepository;this.ids=ids;this.idem=idem;this.audit=audit;this.outbox=outbox;this.mapper=mapper;}
 public record Create(long customerId,Long contactId,String subject,String channel,String summary){} public record AddEntry(SalesConversationEntry.Direction direction,String content,Instant occurredAt){} public record Versioned(long version){} public record Detail(SalesConversation conversation,java.util.List<SalesConversationEntry> entries){}
 @Transactional public SalesConversation create(Actor a,Create c,String key){sales.customer(a,c.customerId()); if(c.contactId()!=null&&salesRepository.findContacts(a.tenantId(),c.customerId()).stream().noneMatch(contact->contact.id()==c.contactId()))throw new DomainException(ErrorCode.VALIDATION_ERROR,"联系人不属于该客户"); return idem.execute(a,"conversation:create",key,c,SalesConversation.class,()->{Instant now=Instant.now();SalesConversation x=new SalesConversation(ids.nextId(),a.tenantId(),c.customerId(),c.contactId(),req(c.subject(),200,"主题"),req(c.channel(),32,"沟通渠道"),SalesConversation.Status.OPEN,trim(c.summary(),2000),a.userId(),null,0,now,now);x=repo.insert(x,a.userId());journal(a,"CREATE",x,"SalesConversationCreated");return x;});}
 public Detail detail(Actor a,long id){SalesConversation x=get(a,id);access(a,x,false);return new Detail(x,repo.entries(a.tenantId(),id));}
 @Transactional public SalesConversation addEntry(Actor a,long id,AddEntry c,String key){SalesConversation x=get(a,id);access(a,x,true); if(x.status()!=SalesConversation.Status.OPEN)throw new DomainException(ErrorCode.CONFLICT,"已关闭会话不能追加记录"); return idem.execute(a,"conversation:entry",key,c,SalesConversation.class,()->{Instant now=Instant.now();repo.append(new SalesConversationEntry(ids.nextId(),a.tenantId(),id,c.direction(),req(c.content(),4000,"沟通内容"),c.occurredAt()==null?now:c.occurredAt(),a.userId(),now));journal(a,"ADD_ENTRY",x,"SalesConversationEntryAdded");return x;});}
 @Transactional public SalesConversation change(Actor a,long id,Versioned c,SalesConversation.Status target){SalesConversation before=get(a,id);access(a,before,true);if(!repo.transition(a.tenantId(),id,c.version(),before.status(),target,a.userId()))throw new DomainException(ErrorCode.CONFLICT,"会话状态已变化，请刷新后重试");SalesConversation after=get(a,id);journal(a,target==SalesConversation.Status.CLOSED?"CLOSE":"REOPEN",after,target==SalesConversation.Status.CLOSED?"SalesConversationClosed":"SalesConversationReopened");return after;}
 private SalesConversation get(Actor a,long id){return repo.find(a.tenantId(),id).orElseThrow(()->new DomainException(ErrorCode.NOT_FOUND,"销售会话不存在"));} private void access(Actor a,SalesConversation x,boolean write){if(x.ownerUserId()==a.userId())return;String p=write?"conversation:write:any":"conversation:read:any";if(!a.hasPermission(p))throw new DomainException(ErrorCode.FORBIDDEN,"缺少权限："+p);} private String req(String v,int n,String f){String x=trim(v,n);if(x==null)throw new DomainException(ErrorCode.VALIDATION_ERROR,f+"不能为空");return x;} private String trim(String v,int n){if(v==null||v.isBlank())return null;String x=v.trim();if(x.length()>n)throw new DomainException(ErrorCode.VALIDATION_ERROR,"字段长度超限");return x;} private void journal(Actor a,String action,SalesConversation x,String event){try{String data=mapper.writeValueAsString(x),op="conversation:"+action+":"+ids.nextId();audit.record(a,action,"SALES_CONVERSATION",x.id(),op,"API",null,"{}",data);outbox.append(new DomainEvent(event,"SALES_CONVERSATION",x.id(),a.tenantId(),data,Instant.now()),op,a.userId());}catch(Exception e){throw new IllegalStateException(e);}}
}
