package com.aicrm.sales.infrastructure;
import com.aicrm.sales.domain.conversation.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.sql.Timestamp; import java.util.*;
@Repository public class JdbcSalesConversationRepository implements SalesConversationRepository {
 private final JdbcTemplate jdbc; public JdbcSalesConversationRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public SalesConversation insert(SalesConversation v,long actor){jdbc.update("insert into crm_sales_conversation (id,tenant_id,customer_id,contact_id,subject,channel,status,summary,owner_user_id,closed_at,version,created_by,updated_by,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",v.id(),v.tenantId(),v.customerId(),v.contactId(),v.subject(),v.channel(),v.status().name(),v.summary(),v.ownerUserId(),null,v.version(),actor,actor,Timestamp.from(v.createdAt()),Timestamp.from(v.updatedAt()));return find(v.tenantId(),v.id()).orElseThrow();}
 public Optional<SalesConversation> find(long tenant,long id){return jdbc.query("select * from crm_sales_conversation where tenant_id=? and id=? and deleted_at is null",rs->rs.next()?Optional.of(map(rs)):Optional.empty(),tenant,id);}
 public List<SalesConversationEntry> entries(long tenant,long id){return jdbc.query("select * from crm_sales_conversation_entry where tenant_id=? and conversation_id=? order by occurred_at,id",(rs,n)->new SalesConversationEntry(rs.getLong("id"),rs.getLong("tenant_id"),rs.getLong("conversation_id"),SalesConversationEntry.Direction.valueOf(rs.getString("direction")),rs.getString("content"),rs.getTimestamp("occurred_at").toInstant(),rs.getLong("created_by"),rs.getTimestamp("created_at").toInstant()),tenant,id);}
 public boolean append(SalesConversationEntry e){return jdbc.update("insert into crm_sales_conversation_entry (id,tenant_id,conversation_id,direction,content,occurred_at,created_by,created_at) values (?,?,?,?,?,?,?,?)",e.id(),e.tenantId(),e.conversationId(),e.direction().name(),e.content(),Timestamp.from(e.occurredAt()),e.createdBy(),Timestamp.from(e.createdAt()))==1;}
 public boolean transition(long tenant,long id,long version,SalesConversation.Status from,SalesConversation.Status to,long actor){return jdbc.update("update crm_sales_conversation set status=?,closed_at=case when ?='CLOSED' then now() else null end,version=version+1,updated_by=?,updated_at=now() where tenant_id=? and id=? and version=? and status=? and deleted_at is null",to.name(),to.name(),actor,tenant,id,version,from.name())==1;}
 private SalesConversation map(java.sql.ResultSet rs)throws java.sql.SQLException { long contact=rs.getLong("contact_id"); Long contactId=rs.wasNull()?null:contact; Timestamp closed=rs.getTimestamp("closed_at"); return new SalesConversation(rs.getLong("id"),rs.getLong("tenant_id"),rs.getLong("customer_id"),contactId,rs.getString("subject"),rs.getString("channel"),SalesConversation.Status.valueOf(rs.getString("status")),rs.getString("summary"),rs.getLong("owner_user_id"),closed==null?null:closed.toInstant(),rs.getLong("version"),rs.getTimestamp("created_at").toInstant(),rs.getTimestamp("updated_at").toInstant()); }
}
