package com.aicrm.web.sales;
import com.aicrm.kernel.security.*; import com.aicrm.sales.application.SalesConversationService; import com.aicrm.sales.domain.conversation.*; import com.aicrm.web.api.ApiResponse; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.List;
@RestController @RequestMapping("/api/v1/sales-conversations") public class SalesConversationV1Controller {
 private final SalesConversationService service; public SalesConversationV1Controller(SalesConversationService service){this.service=service;}
 record CreateRequest(@NotNull Long customerId,Long contactId,@NotBlank String subject,@NotBlank String channel,String summary){} record EntryRequest(@NotNull SalesConversationEntry.Direction direction,@NotBlank String content,Instant occurredAt){} record VersionRequest(@NotNull Long version){} record View(String id,String customerId,String contactId,String subject,String channel,String status,String summary,String ownerUserId,Instant closedAt,long version){} record EntryView(String id,String direction,String content,Instant occurredAt,String createdBy){} record DetailView(View conversation,List<EntryView> entries){}
 @PostMapping public ResponseEntity<ApiResponse<View>> create(@RequestBody CreateRequest r,@RequestHeader("Idempotency-Key")String key){return ResponseEntity.status(HttpStatus.CREATED).body(ok(view(service.create(ActorContext.require(),new SalesConversationService.Create(r.customerId(),r.contactId(),r.subject(),r.channel(),r.summary()),key))));}
 @GetMapping("/{id}") public ApiResponse<DetailView> detail(@PathVariable long id){var d=service.detail(ActorContext.require(),id);return ok(new DetailView(view(d.conversation()),d.entries().stream().map(e->new EntryView(String.valueOf(e.id()),e.direction().name(),e.content(),e.occurredAt(),String.valueOf(e.createdBy()))).toList()));}
 @PostMapping("/{id}/entries") public ApiResponse<View> entry(@PathVariable long id,@RequestBody EntryRequest r,@RequestHeader("Idempotency-Key")String key){return ok(view(service.addEntry(ActorContext.require(),id,new SalesConversationService.AddEntry(r.direction(),r.content(),r.occurredAt()),key)));}
 @PostMapping("/{id}/actions/close") public ApiResponse<View> close(@PathVariable long id,@RequestBody VersionRequest r){return ok(view(service.change(ActorContext.require(),id,new SalesConversationService.Versioned(r.version()),SalesConversation.Status.CLOSED)));}
 @PostMapping("/{id}/actions/reopen") public ApiResponse<View> reopen(@PathVariable long id,@RequestBody VersionRequest r){return ok(view(service.change(ActorContext.require(),id,new SalesConversationService.Versioned(r.version()),SalesConversation.Status.OPEN)));}
 private View view(SalesConversation x){return new View(String.valueOf(x.id()),String.valueOf(x.customerId()),x.contactId()==null?null:String.valueOf(x.contactId()),x.subject(),x.channel(),x.status().name(),x.summary(),String.valueOf(x.ownerUserId()),x.closedAt(),x.version());} private <T>ApiResponse<T>ok(T x){return ApiResponse.success(x,TraceContext.get());}
}
